version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simple_cms_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  app:
    build: .
    working_dir: /simple_cms
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/simple_cms"
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db:db